// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRqcavA30sIz69XsZsEpccFeSK924Gdw',
    appId: '1:534175091732:web:cda28ded1ff44b2140ab01',
    messagingSenderId: '534175091732',
    projectId: 'flutterlogin-ebbd5',
    authDomain: 'flutterlogin-ebbd5.firebaseapp.com',
    storageBucket: 'flutterlogin-ebbd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYw-EoO5h3vjBWZOtGhyBR5a0gQmDdDs',
    appId: '1:534175091732:android:f14a64f052df6b4540ab01',
    messagingSenderId: '534175091732',
    projectId: 'flutterlogin-ebbd5',
    storageBucket: 'flutterlogin-ebbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-kICspV2DEf1E6DueaPg0kPgG52E6kI',
    appId: '1:534175091732:ios:71269621f69f46b340ab01',
    messagingSenderId: '534175091732',
    projectId: 'flutterlogin-ebbd5',
    storageBucket: 'flutterlogin-ebbd5.appspot.com',
    iosClientId: '534175091732-08odrmu8kssk86vfgup0gdhanfr2jict.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-kICspV2DEf1E6DueaPg0kPgG52E6kI',
    appId: '1:534175091732:ios:2ce7a5733fc91c2940ab01',
    messagingSenderId: '534175091732',
    projectId: 'flutterlogin-ebbd5',
    storageBucket: 'flutterlogin-ebbd5.appspot.com',
    iosClientId: '534175091732-kop82efuojnbtor7tlf8vqsi494guq8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
